# I strongly recommend keeping this enabled, because I often release beta and snapshot versions
# so you would get notified when the stable version is released
general:
  update-notify: true

title:
  on_discover:
    enabled: true
    title: "&a&l@area"
    subtitle: "&f@description"
    # Values are in seconds
    fadein: 1
    stay: 3
    fadeout: 1
  on_enter:
    enabled: true
    title: "&a&l@area"
    subtitle: "&f@description"
    fadein: 1
    stay: 3
    fadeout: 1

messages:
  help:
    - "&6&lDiscoverAreas Help"
    - "&e/area &8- &7shows this help"
    - "&e/area create <region> <name> &8- &7create new discoverable area"
    - "&e/area delete <name> &8- &7remove a discoverable area"
    - "&e/area setexp <name> &8- &7set xp reward for area"
    - "&e/area reset [player] &8- &7remove yours/player's progress"
    - "&e/area setdesc <name> &8- &7set area's new description"
    - "&e/area command list <area> &8- &7shows all area's reward commands"
    - "&e/area command add <name> &8- &7add new reward command to area"
    - "&e/area command remove <cmd_id> <area> &8- &7remove reward command"
    - "&e/area command edit <cmd_id> <area> &8- &7edit reward command"
  on_discover:
    enabled: true
    messages:
      - "&a&lYou have discovered @area"
      - "&f"
      - "&f@description"
  on_enter:
    enabled: false
    messages:
      - "&aYou are entering @area"

sounds:
  info: "BLOCK_LADDER_HIT"
  success: "ENTITY_EXPERIENCE_ORB_PICKUP"
  error: "BLOCK_ANVIL_PLACE"
  warning: "BLOCK_BEACON_POWER_SELECT"

menus:
  user:
    enabled: true
    titles:
      nopage: "User menu"
      page: "User menu #@page"
  admin:
    enabled: true
    titles:
      nopage: "Admin menu"
      page: "Admin menu #@page"

gui:
  list:
    admin:
      material: BOOK
      glowing: false
      displayname: "&a@area"
      lore:
        - "&fWorld: &7@world"
        - "&fDescription:"
        - "&7@description"
        - "&6Click to open."
    discovered:
      material: BOOK
      glowing: true
      displayname: "&a@area"
      lore:
        - "&aDiscovered"
        - "&fDescription:"
        - "&7@description"
    notdiscovered:
      material: PAPER
      glowing: false
      displayname: "&c@area"
      lore:
        - "&cNot Discovered"
        - "&fDescription:"
        - "&7@description"
  previous:
    material: ARROW
    displayname: "&7Previous page"
    lore: []
  next:
    material: ARROW
    displayname: "&7Next page"
    lore: []
  stats:
    enabled: true
    material: PAPER
    displayname: "&aStatistics"
    lore:
      - "&7Total areas: &f@areas"


# List of areas and their settings
areas: {}