name: DiscoverAreas
version: 1.4.0-B1
main: net.ignissak.discoverareas.DiscoverMain
api-version: 1.13
depend: [WorldGuard]
authors: [iGniSsak]
commands:
  area:
    usage: /<command>
    description: General command
  ".areas":
    usage: /<command>
    description: Admin menu