name: DiscoverAreas
version: 1.5.0-B1
load: POSTWORLD
main: net.ignissak.discoverareas.DiscoverMain
api-version: 1.13
depend: [WorldGuard]
authors: [iGniSsak]
commands:
  area:
    usage: /area
    description: General command
  ".areas":
    usage: /.areas
    description: Admin menu
  areas:
    usage: /areas
    description: User menu