name: DiscoverAreas
version: 1.5.0-B1-1_12
main: net.ignissak.discoverareas.DiscoverMain
depend: [WorldGuard]
authors: [iGniSsak]
commands:
  area:
    usage: /<command>
    description: General command
  ".areas":
    usage: /<command>
    description: Admin menu