name: DiscoverAreas
load: POSTWORLD
main: net.ignissak.discoverareas.DiscoverMain
depend: [WorldGuard]
authors: [iGniSsak]
commands:
  area:
    usage: /area
    description: General command
  ".areas":
    usage: /.areas
    description: Admin menu
  areas:
    usage: /areas
    description: User menu
permissions:
  discoverareas.*:
    children:
      discoverareas.admin.areas: true
  discoverareas.user:
    default: false
    children: