name: DiscoverAreas
version: 1.7.0-SNAPSHOT
load: POSTWORLD
main: net.ignissak.discoverareas.DiscoverAreasPlugin
api-version: "1.14"
depend: [WorldGuard]
authors: [iGniSsak]
commands:
  area:
    usage: /area
    description: General command'm
  ".areas":
    usage: /.areas
    description: Admin menu
  areas:
    usage: /areas
    description: User menu
permissions:
  discoverareas.*:
    children:
      discoverareas.admin.areas: true
      discoverareas.user: true
  discoverareas.user:
    default: false
    children:
      discoverareas.user.areas: true